name: CI for book
on:
  push:
    branches: [main]
  pull_request:
    paths-ignore:
      - "README.md"
jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
      - name: Install Rust toolchain
        run: |
          rustup toolchain install stable
      - name: Install cargo-related tools
        uses: taiki-e/install-action@v2
        with:
          tool: nextest, cargo-make
      - name: Tests compile
        # --no-run ビルドだけ
        # --locked Cargo.lock が最新状態でない場合にはエラー
        run: cargo make test-ci --no-run --locked
      - name: Clippy
        # -Dwarnings で警告をエラーとして扱う
        run: cargo make clippy-ci -- -Dwarnings
      - name: Rustfmt
        run: cargo make fmt -- --check
